import parse, { BinaryDesc } from "./binaryParser";

// prettier-ignore
const binaryDesc: BinaryDesc[] = [
	{ name: "_00.headerV", type: "char" },
	{ name: "_00.numberOfFrames", type: "char" },
	{ name: "_00.numberOfPreinfuseFrames", type: "char" },
	{ name: "_00.minimumPressure", type: "char", process: "$val / 16.0" },
	{ name: "_00.maximumFlow", type: "char", process: "$val / 16.0" },
	{ name: "_01.flag", type: "char" },
	{ name: "_01.setVal", type: "char", process: "$val / 16.0" },
	{ name: "_01.temp", type: "char", process: "$val / 2.0" },
	{ name: "_01.frameLen", type: "char", process: "[convert_F8_1_7_to_float $val]" },
	{ name: "_01.triggerVal", type: "char", process: "$val / 16.0" },
	{ name: "_01.maxVol", type: "short", process: "[convert_bottom_10_of_U10P0 $val]" },
	{ name: "_02.flag", type: "char" },
	{ name: "_02.setVal", type: "char", process: "$val / 16.0" },
	{ name: "_02.temp", type: "char", process: "$val / 2.0" },
	{ name: "_02.frameLen", type: "char", process: "[convert_F8_1_7_to_float $val]" },
	{ name: "_02.triggerVal", type: "char", process: "$val / 16.0" },
	{ name: "_02.maxVol", type: "short", process: "[convert_bottom_10_of_U10P0 $val]" },
	{ name: "_03.flag", type: "char" },
	{ name: "_03.setVal", type: "char", process: "$val / 16.0" },
	{ name: "_03.temp", type: "char", process: "$val / 2.0" },
	{ name: "_03.frameLen", type: "char", process: "[convert_F8_1_7_to_float $val]" },
	{ name: "_03.triggerVal", type: "char", process: "$val / 16.0" },
	{ name: "_03.maxVol", type: "short", process: "[convert_bottom_10_of_U10P0 $val]" },
	{ name: "_04.flag", type: "char" },
	{ name: "_04.setVal", type: "char", process: "$val / 16.0" },
	{ name: "_04.temp", type: "char", process: "$val / 2.0" },
	{ name: "_04.frameLen", type: "char", process: "[convert_F8_1_7_to_float $val]" },
	{ name: "_04.triggerVal", type: "char", process: "$val / 16.0" },
	{ name: "_04.maxVol", type: "short", process: "[convert_bottom_10_of_U10P0 $val]" },
	{ name: "_05.flag", type: "char" },
	{ name: "_05.setVal", type: "char", process: "$val / 16.0" },
	{ name: "_05.temp", type: "char", process: "$val / 2.0" },
	{ name: "_05.frameLen", type: "char", process: "[convert_F8_1_7_to_float $val]" },
	{ name: "_05.triggerVal", type: "char", process: "$val / 16.0" },
	{ name: "_05.maxVol", type: "short", process: "[convert_bottom_10_of_U10P0 $val]" },
	{ name: "_06.flag", type: "char" },
	{ name: "_06.setVal", type: "char", process: "$val / 16.0" },
	{ name: "_06.temp", type: "char", process: "$val / 2.0" },
	{ name: "_06.frameLen", type: "char", process: "[convert_F8_1_7_to_float $val]" },
	{ name: "_06.triggerVal", type: "char", process: "$val / 16.0" },
	{ name: "_06.maxVol", type: "short", process: "[convert_bottom_10_of_U10P0 $val]" },
	{ name: "_07.flag", type: "char" },
	{ name: "_07.setVal", type: "char", process: "$val / 16.0" },
	{ name: "_07.temp", type: "char", process: "$val / 2.0" },
	{ name: "_07.frameLen", type: "char", process: "[convert_F8_1_7_to_float $val]" },
	{ name: "_07.triggerVal", type: "char", process: "$val / 16.0" },
	{ name: "_07.maxVol", type: "short", process: "[convert_bottom_10_of_U10P0 $val]" },
	{ name: "_08.flag", type: "char" },
	{ name: "_08.setVal", type: "char", process: "$val / 16.0" },
	{ name: "_08.temp", type: "char", process: "$val / 2.0" },
	{ name: "_08.frameLen", type: "char", process: "[convert_F8_1_7_to_float $val]" },
	{ name: "_08.triggerVal", type: "char", process: "$val / 16.0" },
	{ name: "_08.maxVol", type: "short", process: "[convert_bottom_10_of_U10P0 $val]" },
	{ name: "_09.flag", type: "char" },
	{ name: "_09.setVal", type: "char", process: "$val / 16.0" },
	{ name: "_09.temp", type: "char", process: "$val / 2.0" },
	{ name: "_09.frameLen", type: "char", process: "[convert_F8_1_7_to_float $val]" },
	{ name: "_09.triggerVal", type: "char", process: "$val / 16.0" },
	{ name: "_09.maxVol", type: "short", process: "[convert_bottom_10_of_U10P0 $val]" },
	{ name: "_10.flag", type: "char" },
	{ name: "_10.setVal", type: "char", process: "$val / 16.0" },
	{ name: "_10.temp", type: "char", process: "$val / 2.0" },
	{ name: "_10.frameLen", type: "char", process: "[convert_F8_1_7_to_float $val]" },
	{ name: "_10.triggerVal", type: "char", process: "$val / 16.0" },
	{ name: "_10.maxVol", type: "short", process: "[convert_bottom_10_of_U10P0 $val]" }
]

export default (buffer: Buffer) => {
  return parse(buffer, binaryDesc);
};
